---

- name: Check state of installed Logstash plugins
  tags: [ "dfv::logstash:plugins" ]
  shell: bin/logstash-plugin list
  args:
    chdir: '/usr/share/logstash'
  register: logstash__register_plugins
  changed_when: False
  check_mode: False

- name: Install Logstash plugins
  tags: [ "dfv::logstash:plugins" ]
  shell: bin/logstash-plugin install {{ item.path | d(item.name) }}
  args:
    chdir: '/usr/share/logstash'
  notify: [ 'Restart logstash' ]
  with_flattened:
    - '{{ logstash__combined_plugins }}'
  when: (item.name|d() and item.state|d('present') != 'absent' and
         item.name not in logstash__register_plugins.stdout_lines)

- name: Remove Logstash plugins
  tags: [ "dfv::logstash:plugins" ]
  shell: bin/logstash-plugin remove {{ item.name }}
  args:
    chdir: '/usr/share/logstash'
  notify: [ 'Restart logstash' ]
  with_flattened:
    - '{{ logstash__combined_plugins }}'
  when: (item.name|d() and item.state|d('present') == 'absent' and
         item.name in logstash__register_plugins.stdout_lines)


- name: Create Logstash configuration files and filters.
  tags: [ "dfv::logstash:config" ]
  template:
    src: "etc/logstash/conf.d/{{ item }}.j2"
    dest: "/etc/logstash/conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - input.conf
    - filter.conf
    - output.conf

  notify: Restart Logstash


- name: Ensure Logstash is running
  tags: [ "dfv::logstash", "dfv::logstash:config" ]
  service:
    name: logstash
    state: started

